version: "3.9"

services:
   app:
    build:
      context: .
    ports:
      - "8000:8000"
    container_name: appc
    volumes:
      - ./ecommerce:/app
      - maatre-static-data:/staticfiles
      - maatre-media-data:/mediafiles
    environment:
      - DB_HOST=db
      - DB_NAME=${DATABASE_NAME}
      - DB_USERNAME=${DATABASE_USERNAME}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - PORT=5432
      - EMAIL_USERNAME=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      #- DEBUG=${DEBUG}
    depends_on:
      - db

   db:
    image: postgres:13-alpine
    container_name: dbc
    volumes:
      - maatre-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

volumes:
   maatre-db-data:
   maatre-static-data:
   maatre-media-data: