# Generated by Django 4.2.5 on 2023-09-20 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartsummary',
            options={'verbose_name_plural': 'Cart Summary'},
        ),
        migrations.RenameField(
            model_name='cartsummary',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cartsummary',
            old_name='user_id',
            new_name='user',
        ),
    ]
